version: "3.1"
services:
   docker-vps:
      build:
         context: .
         args:
            - USER=${USER:-docker_vps}
      privileged: true # run container in priviliged mode
      deploy:
         replicas: ${REPLICAS:-3} # scale to REPLICAS instances
      volumes:
         - "/var/run/docker.sock:/var/run/docker.sock" # mount the docker socket (necessary for docker in docker)
      ports:
         - "${HOST_PORT:-1000-1010}:22" # expose ports range to the host
